### ISSUE TITLE
Question About The MetroTabControl

### ISSUE THREAD

**Issue by edebdev** [thielj/MetroFramework#1]
Hi,

If i dock something in a metrotabpage, lets say a regular listview, some small gray stripes and black (clickable) blocks appear in the upper left corner of the tabpage as some kind of overlay.

When clicking on one of the blocks this "overlay" disappears again.

Am i just missing something out? I Could attach a Image if you want to.

Thanks!

**Comment by thielj** [comment]
Hi

I could repro it. The original code I had forked is quite messy and I hadn't had time to sort out everything yet, incl. the scrollbar stuff. As I'm heading off to holidays this week, this won't happen in the next 14 days though.

If you don't need the scrollbars at the moment, a quick workaround would be to edit the ctor for MetroTabPage and comment out the scrollbars:

```
    //Controls.Add(verticalScrollbar);
    //Controls.Add(horizontalScrollbar);
```

**Comment by edebdev** [comment]
Great, that helped me out.

have a good time the next 14 days on your holiday.

Thanks!
