### ISSUE TITLE
How do i implement this?

### ISSUE THREAD

**Issue by LiamKenyon** [thielj/MetroFramework#25]
OK, simple and stupid question i know.

I have the package installed on my project, i have all the options in my toolbox.

What i want to know is how to i change the existing form from standard to metro style?

I'm using VB 2013 Express.

**Comment by gofal** [comment]
I think it is not possible to do this in designer.
In the solution-explorer you will find a designer-file for every form. eg if your form is called UIMainForm, then you will find UIMainForm.vb as well as UIMainForm.Designer.vb and UIMainForm.resx.
You have to open the UIMainForm.Designer.vb file and there you see the partial class with the interitance. ( partial class UIMainForm inherits System.Windows.Forms.Form ). Change this to partial class UIMainForm inherits MetroFramework.Forms.MetroForm.

**Comment by LiamKenyon** [comment]
Correct, knew it was simple, thanks very much.

Will help with update of program looks.
