### ISSUE TITLE
Changing the style of a metroTile by clicking in another metroTile at runtime

### ISSUE THREAD

**Issue by adrianabenicio** [thielj/MetroFramework#35]
When I change the style of a metroTile by clicking in another metroTile at runtime, the new color is only set when the mouse passes over the component.

The code I'm using is simply:
        private void mtlClientes_Click(object sender, EventArgs e)
        {
            mtlProdutos.Style = MetroFramework.MetroColorStyle.Orange;
        }

**Comment by adrianabenicio** [comment]
Solved adding:
mtlProdutos.Refresh();

**Comment by zeeshan47** [comment]
have u tried changing forms border color  ?

**Comment by zeeshan47** [comment]
there is no refresh function for stylemanger ?

**Comment by adrianabenicio** [comment]
I solved the problem using
mtlProdutos.Refresh();
