### ISSUE TITLE
Winform maximized issue

### ISSUE THREAD

**Issue by sjayakumar** [thielj/MetroFramework#91]
My system connected in 17" monitor. I selected the extended screen option. if i maximize the metro form, 
in my form some of the controls are hiding. metro form taking the width as total of both screen. Please help me to fix this

**Comment by imedele1** [comment]
Hello Sjayakumar
Did you find an explanation to your problem. I have the same problem and I don't know how to fix it.
For the moment I avoid using MetroFramework because of this problem.

Thank you for your feed-back

**Comment by amnontopel** [comment]
Any update on this one?

**Comment by LuisAndres** [comment]
Any update on this? I need help

**Comment by LuisAndres** [comment]
private void SetMaxBoxSize() {
            int maxwidth = 0;
            int maxheight = 0;
            foreach (var sc in Screen.AllScreens) {               
                if (MaximumSize.Width < sc.WorkingArea.Width) { maxwidth = sc.WorkingArea.Width; }
                if (MaximumSize.Height < sc.WorkingArea.Height) { maxheight = sc.WorkingArea.Height; }}
            MaximumSize = new Size(maxwidth, maxheight);
        }
Added this code in MetroFramework.Forms.MetroForm, in the onLoad method. Works fine.

**Comment by sjayakumar** [comment]
Thank you for sharing details
