### ISSUE TITLE
PromptText on MetroTextBox

### ISSUE THREAD

**Issue by roelpaulo** [thielj/MetroFramework#95]
It doesn't show the Prompt Text when the form loads. You have to type something then clear it before it shows.

**Comment by Delrhani** [comment]
You can edit the textbox in the constructor of your form : 
textBox1.Text = "Something";

Then clear the textbox form
textBox1.Text = "";

**Comment by roelpaulo** [comment]
Clearly this project is dead, thanks anyway.

**Comment by jitendra977** [comment]
thanks for solve
